
server:
  port: 8888
  servlet:
    context-path: /vuejs-api

spring:
  datasource:
    abandon-when-percentage-full: 50
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-interceptors: ConnectionState;StatementFinalizer;ResetAbandonedTimer;SlowQueryReport(threshold=2000)
    log-abandoned: true
    max-active: 10240
    max-idle: 512
    username: root
    password: pekall1234
    remove-abandoned: true
    remove-abandoned-timeout: 90
    suspect-timeout: 60
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    url: jdbc:mysql://localhost:3306/vuejs_api?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    validation-query: SELECT 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
    show-sql: true
